application: share-count
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /.*
  script: index.php
  
- url: /([^/]+)/([^/]+).*
  script: index.php?format=$1&url=$2
